In [1]:
import numpy as np
import pandas as pd
import xgboost as xgb

In [5]:
data_test = pd.read_csv('/Data/test.csv', index_col=0)
data_test

FileNotFoundError: [Errno 2] No such file or directory: '/Data/test.csv'

In [5]:
data_train = pd.read_csv('train.csv')
data_train

,Dates,Category,Descript,DayOfWeek,PdDistrict,Resolution,Address,X,Y
0,2015-05-13 23:53:00,WARRANTS,WARRANT ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",OAK ST / LAGUNA ST,-122.425892,37.774599
1,2015-05-13 23:53:00,OTHER OFFENSES,TRAFFIC VIOLATION ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",OAK ST / LAGUNA ST,-122.425892,37.774599
2,2015-05-13 23:33:00,OTHER OFFENSES,TRAFFIC VIOLATION ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",VANNESS AV / GREENWICH ST,-122.424363,37.800414
3,2015-05-13 23:30:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Wednesday,NORTHERN,NONE,1500 Block of LOMBARD ST,-122.426995,37.800873
4,2015-05-13 23:30:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Wednesday,PARK,NONE,100 Block of BRODERICK ST,-122.438738,37.771541
...,...,...,...,...,...,...,...,...,...
878044,2003-01-06 00:15:00,ROBBERY,ROBBERY ON THE STREET WITH A GUN,Monday,TARAVAL,NONE,FARALLONES ST / CAPITOL AV,-122.459033,37.714056
878045,2003-01-06 00:01:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Monday,INGLESIDE,NONE,600 Block of EDNA ST,-122.447364,37.731948
878046,2003-01-06 00:01:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Monday,SOUTHERN,NONE,5TH ST / FOLSOM ST,-122.403390,37.780266
878047,2003-01-06 00:01:00,VANDALISM,"MALICIOUS MISCHIEF, VANDALISM OF VEHICLES",Monday,SOUTHERN,NONE,TOWNSEND ST / 2ND ST,-122.390531,37.780607
878048,2003-01-06 00:01:00,FORGERY/COUNTERFEITING,"CHECKS, FORGERY (FELONY)",Monday,BAYVIEW,NONE,1800 Block of NEWCOMB AV,-122.394926,37.738212

In [6]:
#some data cleaning
data_train.duplicated().sum()

2323

In [7]:

data_train.isnull().sum()

Dates         0
Category      0
Descript      0
DayOfWeek     0
PdDistrict    0
Resolution    0
Address       0
X             0
Y             0
dtype: int64

In [8]:
data_test.duplicated().sum()

188352

In [9]:
data_test.isnull().sum()

Dates         0
DayOfWeek     0
PdDistrict    0
Address       0
X             0
Y             0
dtype: int64

In [10]:
#drop duplicated values
data_train.drop_duplicates(keep = 'first', inplace = True)
data_train.shape

(875726, 9)

In [11]:
#data preprocessing
X_train = data_train.drop(['Category', 'Resolution', 'Descript'], axis = 1)
X_train

,Dates,DayOfWeek,PdDistrict,Address,X,Y
0,2015-05-13 23:53:00,Wednesday,NORTHERN,OAK ST / LAGUNA ST,-122.425892,37.774599
1,2015-05-13 23:53:00,Wednesday,NORTHERN,OAK ST / LAGUNA ST,-122.425892,37.774599
2,2015-05-13 23:33:00,Wednesday,NORTHERN,VANNESS AV / GREENWICH ST,-122.424363,37.800414
3,2015-05-13 23:30:00,Wednesday,NORTHERN,1500 Block of LOMBARD ST,-122.426995,37.800873
4,2015-05-13 23:30:00,Wednesday,PARK,100 Block of BRODERICK ST,-122.438738,37.771541
...,...,...,...,...,...,...
878044,2003-01-06 00:15:00,Monday,TARAVAL,FARALLONES ST / CAPITOL AV,-122.459033,37.714056
878045,2003-01-06 00:01:00,Monday,INGLESIDE,600 Block of EDNA ST,-122.447364,37.731948
878046,2003-01-06 00:01:00,Monday,SOUTHERN,5TH ST / FOLSOM ST,-122.403390,37.780266
878047,2003-01-06 00:01:00,Monday,SOUTHERN,TOWNSEND ST / 2ND ST,-122.390531,37.780607
878048,2003-01-06 00:01:00,Monday,BAYVIEW,1800 Block of NEWCOMB AV,-122.394926,37.738212

In [12]:
y_train = data_train['Category']
y_train

0                       WARRANTS
1                 OTHER OFFENSES
2                 OTHER OFFENSES
3                  LARCENY/THEFT
4                  LARCENY/THEFT
                   ...
878044                   ROBBERY
878045             LARCENY/THEFT
878046             LARCENY/THEFT
878047                 VANDALISM
878048    FORGERY/COUNTERFEITING
Name: Category, Length: 875726, dtype: object

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
le = LabelEncoder()
y_train = le.fit_transform(y_train)

In [15]:
y_train

array([37, 21, 21, ..., 16, 35, 12])

In [16]:
#X_train['Descript'] = le.fit_transform(X_train['Descript'])
X_train['PdDistrict'] = le.fit_transform(X_train['PdDistrict'])

In [17]:
X_train['DayOfWeek'] = le.fit_transform(X_train['DayOfWeek'])
X_train['Address'] = le.fit_transform(X_train['Address'])
X_train['Dates'] = le.fit_transform(X_train['Dates'])

In [18]:
X_train

         Dates  DayOfWeek  PdDistrict  Address           X          Y
0       389256          6           4    19790 -122.425892  37.774599
1       389256          6           4    19790 -122.425892  37.774599
2       389255          6           4    22697 -122.424363  37.800414
3       389254          6           4     4266 -122.426995  37.800873
4       389254          6           5     1843 -122.438738  37.771541
...        ...        ...         ...      ...         ...        ...
878044       1          1           8    15816 -122.459033  37.714056
878045       0          1           2    11491 -122.447364  37.731948
878046       0          1           7    11315 -122.403390  37.780266
878047       0          1           7    22308 -122.390531  37.780607
878048       0          1           0     5128 -122.394926  37.738212

[875726 rows x 6 columns]

In [19]:
#feature scaling with standard scaler
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
#X_test = sc.transform(X_test)

In [20]:
# XGBoost model
from xgboost import XGBClassifier
model = XGBClassifier()
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              objective='multi:softprob', predictor=None, ...)

In [21]:
X_test = data_test
X_test

,Dates,DayOfWeek,PdDistrict,Address,X,Y
Id,,,,,,
0,2015-05-10 23:59:00,Sunday,BAYVIEW,2000 Block of THOMAS AV,-122.399588,37.735051
1,2015-05-10 23:51:00,Sunday,BAYVIEW,3RD ST / REVERE AV,-122.391523,37.732432
2,2015-05-10 23:50:00,Sunday,NORTHERN,2000 Block of GOUGH ST,-122.426002,37.792212
3,2015-05-10 23:45:00,Sunday,INGLESIDE,4700 Block of MISSION ST,-122.437394,37.721412
4,2015-05-10 23:45:00,Sunday,INGLESIDE,4700 Block of MISSION ST,-122.437394,37.721412
...,...,...,...,...,...,...
884257,2003-01-01 00:01:00,Wednesday,MISSION,2600 Block of BRYANT ST,-122.408983,37.751987
884258,2003-01-01 00:01:00,Wednesday,NORTHERN,1900 Block of WASHINGTON ST,-122.425342,37.792681
884259,2003-01-01 00:01:00,Wednesday,INGLESIDE,5500 Block of MISSION ST,-122.445418,37.712075
884260,2003-01-01 00:01:00,Wednesday,BAYVIEW,1500 Block of HUDSON AV,-122.387394,37.739479
884261,2003-01-01 00:01:00,Wednesday,TARAVAL,1500 Block of SLOAT BL,-122.489714,37.733950

In [22]:
#X_test['Descript'] = le.fit_transform(X_test['Descript'])
X_test['PdDistrict'] = le.fit_transform(X_test['PdDistrict'])
X_test['DayOfWeek'] = le.fit_transform(X_test['DayOfWeek'])
X_test['Address'] = le.fit_transform(X_test['Address'])
X_test['Dates'] = le.fit_transform(X_test['Dates'])

In [23]:
X_test = sc.transform(X_test)

In [24]:
preds = model.predict(X_test)
preds

array([21, 21, 16, ...,  1, 21, 16])

In [27]:
output = pd.DataFrame({"Id":data_test.index, "Predictions":preds})
output.to_csv('submission.csv', index=False)

In [ ]:
#my resulting predictions are not in the samne format as the sampleSsubmission file, and i was unable to figure out how to get 
#my results into that output format, so i was unable to compare my predictions with the samples to get metric scores and was
#unable to submit the file to the competition.